"""add initial currency and price history tables

Revision ID: 0cd192da8dc1
Revises: 
Create Date: 2025-03-02 22:20:47.895574

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cd192da8dc1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("currencies",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("ticker", sa.String(length=4), nullable=False),
    sa.Column("full_name", sa.String(length=20), nullable=False),
    sa.Column("max_supply", sa.Integer(), nullable=True),
    sa.Column("circulating_supply", sa.Integer(), nullable=False),
    sa.Column("last_updated", sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("full_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currencies")
    # ### end Alembic commands ###
