"""add price_history table

Revision ID: 68ffe0853d29
Revises: 0cd192da8dc1
Create Date: 2025-03-02 22:34:02.293101

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68ffe0853d29"
down_revision: str | None = "0cd192da8dc1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("price_history",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("currency_id", sa.Integer(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("market_cap", sa.Numeric(precision=24, scale=16), nullable=False),
    sa.Column("market_cap_dominance", sa.Float(), nullable=False),
    sa.Column("price", sa.Numeric(precision=24, scale=24), nullable=False),
    sa.Column("volume_24h", sa.Numeric(precision=24, scale=16), nullable=False),
    sa.Column("max_supply", sa.Integer(), nullable=True),
    sa.Column("circulating_supply", sa.Integer(), nullable=False),
    sa.Column("percent_change_1h", sa.Float(), nullable=False),
    sa.Column("percent_change_24h", sa.Float(), nullable=False),
    sa.Column("percent_change_30d", sa.Float(), nullable=False),
    sa.Column("percent_change_60d", sa.Float(), nullable=False),
    sa.Column("percent_change_7d", sa.Float(), nullable=False),
    sa.Column("percent_change_90d", sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(["currency_id"], ["currencies.id"] ),
    sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("price_history")
    # ### end Alembic commands ###
