"""migrate to imperative mapping

Revision ID: d29c770374e4
Revises: 
Create Date: 2025-04-11 16:35:44.310322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29c770374e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=4), nullable=True),
    sa.Column('full_name', sa.String(length=20), nullable=True),
    sa.Column('max_supply', sa.Integer(), nullable=True),
    sa.Column('circulating_supply', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currencies')),
    sa.UniqueConstraint('full_name', name=op.f('uq_currencies_full_name'))
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=16), nullable=False),
    sa.Column('market_cap_dominance', sa.Float(), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=24), nullable=False),
    sa.Column('volume_24h', sa.Numeric(precision=24, scale=16), nullable=False),
    sa.Column('circulating_supply', sa.Integer(), nullable=True),
    sa.Column('percent_change_1h', sa.Float(), nullable=False),
    sa.Column('percent_change_24h', sa.Float(), nullable=False),
    sa.Column('percent_change_30d', sa.Float(), nullable=False),
    sa.Column('percent_change_60d', sa.Float(), nullable=False),
    sa.Column('percent_change_7d', sa.Float(), nullable=False),
    sa.Column('percent_change_90d', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], name=op.f('fk_price_history_currency_id_currencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_table('currencies')
    # ### end Alembic commands ###
