"""remove max_supply from the price history

Revision ID: f8794e7358ab
Revises: 68ffe0853d29
Create Date: 2025-03-18 22:59:04.228707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8794e7358ab'
down_revision: Union[str, None] = '68ffe0853d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_history', 'max_supply')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('max_supply', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
